# Site settings
title: Audiodd
email: groupe@audiodd.band
description: > # this means to ignore newlines until "baseurl:"
  Groupe de rock progressif à Marseille. Ils sont trop géniaux !
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.audiodd.band" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  audiodd

# Build settings
markdown: kramdown
